In [2]:
import numpy as np
import pandas as pd

In [ ]:
lista = [1,2,3,4,5]
print (lista)

[1, 2, 3, 4, 5]


In [ ]:
myarray = np.array(lista)
print (myarray)

[1 2 3 4 5]


In [ ]:
print (myarray ** 2)

[ 1  4  9 16 25]


In [ ]:
aocubo = np.power (myarray, 3)
print (aocubo)

In [ ]:
numeros = np.array([1,4,9,16,25,36])
print (np.sqrt(numeros))

[1. 2. 3. 4. 5. 6.]


In [ ]:
np.arange (1,100)

In [ ]:
import numpy as np

valores = np.linspace(0, 10, 5)  # Cria 10 valores igualmente espaçados de 0 a 10
print(np.round(valores, 2))       # Arredonda para 2 casas decimais


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
# Atividade 1

# Exemplo usando arange
arr_arange = np.arange(0, 10)
print("Array com arange:", arr_arange)

# Exemplo usando linspace
arr_linspace = np.linspace(0, 100, 15)
print("Array com linspace:", arr_linspace)


Array com arange: [0 1 2 3 4 5 6 7 8 9]
Array com linspace: [  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]


In [ ]:
# Atividade 2

# Exemplo de power() e sqrt()
random_integers = np.random.randint(1, 11, 5)
print("Array original:", random_integers)

# Power (elevando ao quadrado)
squared = np.power(random_integers, 2)
print("Quadrados dos números:", squared)

# Sqrt (raiz quadrada)
sqrt_values = np.sqrt(random_integers)
print("Raízes quadradas:", sqrt_values)

In [ ]:
# Atividade 3

# Criando o array
arr = np.linspace(0, 5, 10)
print("Array gerado:", arr)

# Power (elevando ao cubo)
cubed = np.power(arr, 3)
print("Potência de 3:", cubed)

# Sqrt (raiz quadrada)
sqrt_arr = np.sqrt(arr)
print("Raízes quadradas:", sqrt_arr)


In [ ]:
diferenca = df_btc['close'] - df_btc['open']
print (diferenca)

In [ ]:
# Defina o valor do dólar em reais
cotacao_dolar = 5.00

# Crie a nova coluna 'Close_BRL' com os valores convertidos
df_btc['close_BRL'] = df_btc['close'] * cotacao_dolar


# Visualize o resultado
df_btc[['close', 'close_BRL']].head()

# Na tabela original
df_btc

In [ ]:
# df.iloc[{linha},{coluna}]
print (df_btc.iloc[0,0])

1514764740
